import { useState, useMemo, useEffect } from "react";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Search } from "lucide-react";
import { format } from "date-fns";

// 🔹 Replace this with your actual store later
const mockReports = [
  {
    id: 1,
    report_name: "Loan Summary",
    generated_by: "Admin",
    total_amount: 50000,
    status: "completed",
    created_at: new Date(),
  },
  {
    id: 2,
    report_name: "Monthly Collection",
    generated_by: "Staff",
    total_amount: 32000,
    status: "pending",
    created_at: new Date(),
  },
];

export function ReportsPage() {
  const [searchQuery, setSearchQuery] = useState("");
  const [reports, setReports] = useState([]);

  useEffect(() => {
    // 🔹 Replace with fetchReports()
    setReports(mockReports);
  }, []);

  const filteredReports = useMemo(() => {
    return reports.filter(
      (report) =>
        report.report_name?.toLowerCase().includes(searchQuery.toLowerCase()) ||
        report.generated_by?.toLowerCase().includes(searchQuery.toLowerCase()),
    );
  }, [reports, searchQuery]);

  return (
    <div className="space-y-6 w-full">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold">Reports</h1>
        <p className="text-muted-foreground mt-1">
          View and manage generated reports
        </p>
      </div>

      {/* Card */}
      <Card>
        <CardHeader>
          <CardTitle>All Reports</CardTitle>

          {/* Search */}
          <div className="flex items-center gap-2 mt-4">
            <div className="relative flex-1 max-w-md">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input
                placeholder="Search reports..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="pl-9"
              />
            </div>
          </div>
        </CardHeader>

        <CardContent>
          {filteredReports.length === 0 ? (
            <div className="text-center py-12">
              <p className="text-muted-foreground">
                {searchQuery ? "No reports found" : "No reports yet"}
              </p>
            </div>
          ) : (
            <div className="rounded-md border">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Report Name</TableHead>
                    <TableHead>Generated By</TableHead>
                    <TableHead>Total Amount</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead>Date Created</TableHead>
                  </TableRow>
                </TableHeader>

                <TableBody>
                  {filteredReports.map((report) => (
                    <TableRow key={report.id}>
                      <TableCell className="font-medium">
                        {report.report_name}
                      </TableCell>

                      <TableCell>{report.generated_by}</TableCell>

                      <TableCell>
                        ₱ {report.total_amount.toLocaleString()}
                      </TableCell>

                      <TableCell>
                        <span
                          className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                            report.status === "completed"
                              ? "bg-green-100 text-green-800 dark:bg-green-900/20 dark:text-green-400"
                              : "bg-yellow-100 text-yellow-800 dark:bg-yellow-900/20 dark:text-yellow-400"
                          }`}
                        >
                          {report.status}
                        </span>
                      </TableCell>

                      <TableCell>
                        {format(new Date(report.created_at), "MMM dd, yyyy")}
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
